# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20170308_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='budget',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.Budget'),
            preserve_default=False,
        ),
    ]
