# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 05:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_section_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='trans_description',
        ),
    ]
